name: Flutter Build

on:
  push:
    branches:
      - main # Trigger on commits to the main branch
  pull_request:
    branches:
      - main # Trigger on pull requests to the main branch

jobs:
  build:
    runs-on: ubuntu-latest # Use the latest Ubuntu runner

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Flutter
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.13.0' # Specify your Flutter version

      # Install dependencies
      - name: Install dependencies
        run: flutter pub get

      # Run tests (optional)
      - name: Run tests
        run: flutter test

      # Build the app
      - name: Build APK
        run: flutter build apk --release

      # Build the app for iOS (optional, requires macOS runner)
      # - name: Build iOS
      #   run: flutter build ios --release
      #   if: runner.os == 'macOS'

      # Upload build artifacts (optional)
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-release.apk
          path: build/app/outputs/flutter-apk/app-release.apk
