name: Flutter Build

on:
  push:
    branches:
      - main # Trigger on commits to the main branch
      - develop
  pull_request:
    branches:
      - main # Trigger on pull requests to the main branch
      - develop

jobs:
  build:
    runs-on: 
      - ubuntu-latest # Use the latest Ubuntu runner
      #- macos-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Flutter
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.27.4' # Specify your Flutter version

      # Install dependencies
      - name: Install dependencies
        run: flutter pub get

      # Run static analysis
#             - name: Run static analysis
#                  run: flutter analyze

      # Run formatting checks
#            - name: Run formatting checks
#                  run: flutter format --set-exit-if-changed .

      # Run tests with coverage
      - name: Run tests with coverage
        run: flutter test --coverage

      # Install lcov
      - name: Install lcov
        run: sudo apt-get install lcov

      # Generate coverage report
      #- name: Generate coverage report
      #  run: lcov --capture --directory coverage --output-file coverage/lcov.info

      # Generate HTML coverage report
      - name: Generate HTML coverage report
        run: genhtml -o coverage coverage/lcov.info

      # Upload coverage report
      - name: Upload coverage report
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: coverage/lcov.info

      # Upload HTML coverage report
      - name: Upload HTML coverage report
        uses: actions/upload-artifact@v4
        with:
          name: html-coverage-report
          path: coverage/index.html

      # Upload coverage to Codecov
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}

      # Build the app
      - name: Build APK
        run: flutter build apk --release

      # Upload build artifacts (optional)
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-release.apk
          path: build/app/outputs/flutter-apk/app-release.apk

      # Cache Flutter dependencies
      - name: Cache Flutter dependencies
        uses: actions/cache@v3
        with:
          path: sunny16/.flutter # Cache Flutter SDK
          key: flutter-dependencies-${{ runner.os }}-${{ hashFiles('sunny16/pubspec.lock') }}
          restore-keys: |
            flutter-dependencies-${{ runner.os }}-
